#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

secret=$(ynh_string_random --length=24)
ynh_app_setting_set --key="secret" --value="$secret"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding app's configuration file..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
     ynh_hide_warnings npm install next --force
     ynh_hide_warnings npx playwright install --with-deps chromium
     ynh_hide_warnings yarn build
     ynh_hide_warnings yarn prisma migrate deploy
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
