#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"
ynh_setup_source --source_id=monolith  --dest_dir="$install_dir/monolith" 
chmod +x "$install_dir/monolith/monolith"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --log="systemd"

ynh_config_add_logrotate

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

pushd "$install_dir"
    ynh_hide_warnings corepack enable
	ynh_hide_warnings env NODE_OPTIONS="--max-old-space-size=2048" yarn workspaces focus linkwarden @linkwarden/web @linkwarden/worker
    ynh_hide_warnings env NODE_OPTIONS="--max-old-space-size=2048" yarn prisma:generate
    ynh_hide_warnings env NODE_OPTIONS="--max-old-space-size=2048" yarn web:build
    ynh_hide_warnings env NODE_OPTIONS="--max-old-space-size=2048" yarn prisma:deploy
    export PLAYWRIGHT_BROWSERS_PATH="$install_dir/.cache/ms-playwright"
    npx playwright install chromium
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Starting link processing" --log_path="systemd"
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
